homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.8338442
  longitude: -122.3248267
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 124
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
  # Customize windows and doors
  customize_glob: !include customize_glob.yaml

# System health
system_health:

# Show links to resources in log and frontend
# introduction:

logger:
  default: info
  logs:
    homeassistant.components.mcp23017: debug

# Enables the frontend
frontend:
  themes: !include themes.yaml
  
# Lovelace User Interface
lovelace:
  mode: yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url 

duckdns:
  domain: jardi
  access_token: !secret duckdns_token
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

notify:
  - name: jardi_smtp
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret email
    encryption: starttls
    username: !secret email
    password: !secret gmail_password
    recipient:
      - !secret wife_phone
      - !secret jardi_phone
    sender_name: My Home Assistant

# Discover some devices automatically
discovery:
  ignore:
    - samsung_tv

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track devices connected to my router Actiontec (Frontier FIOS)
device_tracker:
  - platform: quantum_gateway
    host: 192.168.1.1
    password: !secret router_password
    new_device_defaults:
      track_new_devices: false
  - platform: tile
    username: !secret email
    password: !secret tile_password
    monitored_variables: PHONE

# Robot Vacuum cleaner
vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.18
    token: !secret xiaomi_vacuum_token 

# Set up for todoist list
calendar:
  - platform: todoist
    token: !secret todoist_token 
    custom_projects:
      - name: 'Trash This Week'
        due_date_days: 7
        include_projects:
          - Trash Schedule

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor: !include sensors.yaml

# Nest Components
nest:
  client_id: 3d1cccb7-a4c2-4869-86e5-3b4b0313310c
  client_secret: !secret nest_secret
  sensors:
    monitored_conditions:
      #- 'eta'
      - 'humidity'
      #- 'operation_mode'
      - 'temperature'
      - 'target'
  binary_sensors:
    monitored_conditions:
      - 'away'
      #- 'online'
      - 'fan'
      #- 'is_locked'
      - 'has_leaf'
      - 'motion_detected'

# Binary sensors
binary_sensor: !include binary_sensors.yaml

# Switches
# switch:
#  - platform: tplink
#    host: 192.168.1.156

#switch:
#  - platform: mcp23017
#    i2c_address: 0x21
#    pins:
#      15: Test LED

# Samsung TV
media_player:
  - platform: samsungtv
    host: 192.168.1.159
    port: 8001
    mac: 5c:49:7d:63:98:34
    name: Living Room TV

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
