#  Lovelace UI configuration file
title: Home
views:
  # Upstairs Area
  - !include lovelace/view_Upstairs.yaml
  # Downstairs Area
  - !include lovelace/view_Downstairs.yaml
  # Weather Station Data
  - !include lovelace/view_weather_station.yaml
  # Tasks from todoist platform
  - title: Tasks
    icon: 'mdi:calendar-check'
    cards:
      # Garbage Pick Up Schedule
      - type: entities
        show_header_toggle: false
        title: Garbage Pick Up
        entities:
          - sensor.garbage_main
          - sensor.garbage_byweekly

  # Automations and Scripts
  - title: Automations
    icon: 'mdi:home-automation'
    cards:
      # Automations
      - type: entities
        title: Automations
        show_header_toggle: true
        entities:
          - automation.front_door_open
          - automation.arriving_home_turn_on_light
          - automation.open_front_door_turn_on_light
          - automation.notify_if_door_window_left_open
          - automation.front_light_on_before_sunset
          - automation.front_light_off_at_sunrise
      # Scripts
      - type: entities
        title: Scripts
        show_header_toggle: true
        entities:
          - script.play_sound
          - script.send_notification
